// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'color-names'
  | 'column-label'
  | 'menu-sort-by-group'
  | 'page-abbreviation'
  | 'pref-appearance-title'
  | 'pref-base-sort'
  | 'pref-base-sort-creator'
  | 'pref-base-sort-title'
  | 'pref-bg-enabled'
  | 'pref-citation-dialog'
  | 'pref-color-mode'
  | 'pref-color-mode-fixed'
  | 'pref-color-mode-random'
  | 'pref-contour-enabled'
  | 'pref-enable'
  | 'pref-enable-description'
  | 'pref-indent'
  | 'pref-reset-colors'
  | 'pref-sorting-title'
  | 'pref-title'
  | 'prefs-title';
