// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "baseSort": string;
      "indent": number;
      "bgEnabled": boolean;
      "bgColor": string;
      "contourEnabled": boolean;
      "contourColor": string;
      "colorMode": string;
      "groupColors": string;
      "citationDialog": boolean;
      "restoreGroupSort": boolean;
    };
  }
}
